services:
  influxdb:
    image: influxdb:1.8
    container_name: sandbox-influxdb-1
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_HTTP_AUTH_ENABLED=false

  telegraf:
    image: telegraf:latest
    container_name: sandbox-telegraf-1
    privileged: true
    environment:
      - HOSTNAME=telegraf-getting-started
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:Z
      - /var/run/docker.sock:/var/run/docker.sock:Z
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
    links:
      - influxdb
    ports:
      - "8092:8092/udp"
      - "8094:8094"
      - "8125:8125/udp"
    depends_on:
      - influxdb
    restart: unless-stopped

  chronograf:
    image: chronograf:1.8
    container_name: sandbox-chronograf-1
    ports:
      - "8888:8888"
    command: chronograf --influxdb-url=http://sandbox-influxdb-1:8086
    depends_on:
      - influxdb
      - telegraf
